config/routes.rb
Poster::Engine.routes.draw do
  resources :comments

  resources :feeds

end

app/models/poster/comment.rb
module Poster
  class Comment < ActiveRecord::Base
  end
end

app/models/poster/feed.rb
module Poster
  class Feed < ActiveRecord::Base
  end
end

app/controllers/poster/application_controller.rb
class Poster::ApplicationController < ApplicationController
end

app/controllers/poster/comments_controller.rb
require_dependency "poster/application_controller"

module Poster
  class CommentsController < ApplicationController
    before_action :set_comment, only: [:show, :edit, :update, :destroy]

    # GET /comments
    def index
      @comments = Comment.all
    end

    # GET /comments/1
    def show
    end

    # GET /comments/new
    def new
      @comment = Comment.new
    end

    # GET /comments/1/edit
    def edit
    end

    # POST /comments
    def create
      @comment = Comment.new(comment_params)

      if @comment.save
        redirect_to @comment, notice: 'Comment was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /comments/1
    def update
      if @comment.update(comment_params)
        redirect_to @comment, notice: 'Comment was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /comments/1
    def destroy
      @comment.destroy
      redirect_to comments_url, notice: 'Comment was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_comment
        @comment = Comment.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def comment_params
        params.require(:comment).permit(:feed_id, :body)
      end
  end
end

app/controllers/poster/feeds_controller.rb
require_dependency "poster/application_controller"

module Poster
  class FeedsController < ApplicationController
    before_action :set_feed, only: [:show, :edit, :update, :destroy]

    # GET /feeds
    def index
      @feeds = Feed.all
    end

    # GET /feeds/1
    def show
    end

    # GET /feeds/new
    def new
      @feed = Feed.new
    end

    # GET /feeds/1/edit
    def edit
    end

    # POST /feeds
    def create
      @feed = Feed.new(feed_params)

      if @feed.save
        redirect_to @feed, notice: 'Feed was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /feeds/1
    def update
      if @feed.update(feed_params)
        redirect_to @feed, notice: 'Feed was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /feeds/1
    def destroy
      @feed.destroy
      redirect_to feeds_url, notice: 'Feed was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_feed
        @feed = Feed.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def feed_params
        params.require(:feed).permit(:body)
      end
  end
end

app/helpers/poster/application_helper.rb
module Poster
  module ApplicationHelper
  end
end

app/helpers/poster/comments_helper.rb
module Poster
  module CommentsHelper
  end
end

app/helpers/poster/feeds_helper.rb
module Poster
  module FeedsHelper
  end
end

app/views/poster/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feed_id %><br>
    <%= f.number_field :feed_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poster/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/poster/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Feed</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.feed_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/poster/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/poster/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feed:</strong>
  <%= @comment.feed_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/poster/feeds/_form.html.erb
<%= form_for(@feed,:onclick => "return false;") do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poster/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/poster/feeds/index.html.erb
<h1>Listing feeds</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.body %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/poster/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>
<%= javascript_include_tag "poster/jquery","poster/require.js", "poster/app.js" %>

app/views/poster/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @feed.body %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>